Problem\
Use the SOR method to solve the linear system Ax = b, where the entries of
A and b are \
$$
a_{i,j} =
\begin{cases}
2i & \text{when } j=i \text{ and } i = 1,2,...,N \\
0.5i & \text{when }  
\begin{cases}
j=i+2 \text{ and } i = 1,2,....,N-2\\
j=i-2 \text{ and } i = 3,4,....,N\\
\end{cases}\\
0.25i & \text{when }
\begin{cases}
j=i+4 \text{ and } i = 1,2,....,N-4\\
j=i-4 \text{ and } i = 5,6,....,N\\
\end{cases}\\
0 & \text{,otherwise}
\end{cases}
$$
and b<sub>i</sub> = π ,for each i = 1,2,....,N

* Set N =160 (or larger) and run SOR for different $ω = 0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4 .$
* Set the tolerance TOL = 10^(-6) and using the norm $||x^{(k)}-x^{(k-1)}||_{∞}$ as the stopping criterion.
* Output a table that shows the number of iterations and $||x^{(k)}-x^{(k-1)}||_{∞}$ of final approximate solutions for different values of $ω$



# 以下是作業的解答，但我們還需要做一些確認，確認我的程式碼是沒有問題的

In [ ]:
import numpy as np

def construct_matrix_A(N):
    A = np.zeros((N, N))
    for i in range(N):
        A[i, i] = 2 * (i + 1)
        if i + 2 < N:
            A[i, i + 2] = 0.5 * (i + 1)
            A[i + 2, i] = 0.5 * (i + 3)
        if i + 4 < N:
            A[i, i + 4] = 0.25 * (i + 1)
            A[i + 4, i] = 0.25 * (i + 5)
    return A

def sor(A, b, omega, tol=10**(-6), max_iterations=100000):
    N = len(A)
    x = np.zeros(N)
    x_new = np.copy(x)

    for iteration in range(max_iterations):
        for i in range(N):
            sums = np.dot(A[i, :i], x_new[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sums)

        # 計算infinite norm
        diff = x_new - x
        max_diff = max(abs(diff))

        if max_diff < tol:
            return x_new, iteration + 1, max_diff
        else:
            x = np.copy(x_new)

    return x, max_iterations, max_diff

N = 160
A = construct_matrix_A(N)
b = np.pi * np.ones(N)

omegas = [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
results = []

for omega in omegas:
    solution, iterations, norm = sor(A, b, omega)
    results.append((omega, iterations, norm, solution))

# 輸出結果
for result in results:
    print(f"Omega: {result[0]}, Iterations: {result[1]}, Final Norm: {result[2]:.10f}, Solution : {result[3:]}")


Omega: 0.7, Iterations: 16, Final Norm: 0.0000007604, Solution : (array([1.53873402, 0.73142101, 0.10796969, 0.17328405, 0.04055738,
       0.08524885, 0.16644781, 0.12197956, 0.10124957, 0.09045724,
       0.0720288 , 0.07026343, 0.06875489, 0.06324375, 0.05971138,
       0.05570893, 0.05187483, 0.04924599, 0.04677837, 0.04448361,
       0.04246547, 0.04053499, 0.03876907, 0.03717875, 0.03570504,
       0.034348  , 0.03309202, 0.03191915, 0.03082686, 0.02980714,
       0.02885207, 0.02795668, 0.02711504, 0.02632223, 0.02557441,
       0.02486776, 0.02419901, 0.02356524, 0.02296374, 0.02239212,
       0.02184821, 0.02133004, 0.02083584, 0.02036398, 0.01991299,
       0.01948151, 0.0190683 , 0.01867223, 0.01829226, 0.01792742,
       0.01757684, 0.01723968, 0.0169152 , 0.0166027 , 0.01630152,
       0.01601106, 0.01573076, 0.01546009, 0.01519858, 0.01494575,
       0.01470119, 0.0144645 , 0.0142353 , 0.01401325, 0.01379802,
       0.01358928, 0.01338677, 0.0131902 , 0.01299931, 0.012813

## 我想先檢查矩陣輸出是否正確,n就用小一點的數來檢查，下面我用n=7來檢查

In [ ]:
import numpy as np

def construct_matrix_A(N):
    A = np.zeros((N, N))
    for i in range(N):
        A[i, i] = 2 * (i + 1)
        if i + 2 < N:
            A[i, i + 2] = 0.5 * (i + 1)
            A[i + 2, i] = 0.5 * (i + 3)
        if i + 4 < N:
            A[i, i + 4] = 0.25 * (i + 1)
            A[i + 4, i] = 0.25 * (i + 5)
    return A

N = 7
A = construct_matrix_A(N)
print(A)

[[ 2.    0.    0.5   0.    0.25  0.    0.  ]
 [ 0.    4.    0.    1.    0.    0.5   0.  ]
 [ 1.5   0.    6.    0.    1.5   0.    0.75]
 [ 0.    2.    0.    8.    0.    2.    0.  ]
 [ 1.25  0.    2.5   0.   10.    0.    2.5 ]
 [ 0.    1.5   0.    3.    0.   12.    0.  ]
 [ 0.    0.    1.75  0.    3.5   0.   14.  ]]


看起來是正確的，這表示我的矩陣輸出沒有錯

## 接下來我們檢查範例，看看結果是否會和範例相同

In [ ]:
import numpy as np

#def construct_matrix_A(N):
#    A = np.zeros((N, N))
#    for i in range(N):
#        A[i, i] = 2 * (i + 1)
#        if i + 2 < N:
#            A[i, i + 2] = 0.5 * (i + 1)
#            A[i + 2, i] = 0.5 * (i + 3)
#        if i + 4 < N:
#            A[i, i + 4] = 0.25 * (i + 1)
#            A[i + 4, i] = 0.25 * (i + 5)
#    return A

def sor(A, b, omega, tol=10**(-6), max_iterations=100000):
    N = len(A)
    x = np.zeros(N)
    x_new = np.copy(x)
    x_solution = []

    for iteration in range(max_iterations):
        for i in range(N):
            sums = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sums)

        # 計算infinite norm
        diff = x_new - x
        max_diff = max(abs(diff))

        #紀錄x的值
        x_solution.append(np.copy(x))

        if max_diff < tol:
            return x_new, iteration + 1, max_diff,x_solution
        else:
           x = np.copy(x_new)

    return x, max_iterations, max_diff, x_solution

N = 4
A = np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
b = [6,25,-11,15]

omegas = [1.0]
results = []

for omega in omegas:
    solution, iterations, norm ,x_solution = sor(A, b, omega)
    results.append((omega, iterations, norm))

print("矩陣Ａ是")
print(A)

# 輸出結果
print("This way is Jacobi's Iterative")
for result in results:
    print(f"Omega: {result[0]}, Iterations: {result[1]}, Final Norm: {result[2]:.10f}")

i = 0
for x in x_solution:
    formatted_x = [f"{val:.4f}" for val in x]
    print(f"第{i}個解：x = {formatted_x}")
    i += 1
#print(solution)

矩陣Ａ是
[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]]
This way is Jacobi's Iterative
Omega: 1.0, Iterations: 18, Final Norm: 0.0000008731
第0個解：x = ['0.0000', '0.0000', '0.0000', '0.0000']
第1個解：x = ['0.6000', '2.2727', '-1.1000', '1.8750']
第2個解：x = ['1.0473', '1.7159', '-0.8052', '0.8852']
第3個解：x = ['0.9326', '2.0533', '-1.0493', '1.1309']
第4個解：x = ['1.0152', '1.9537', '-0.9681', '0.9738']
第5個解：x = ['0.9890', '2.0114', '-1.0103', '1.0214']
第6個解：x = ['1.0032', '1.9922', '-0.9945', '0.9944']
第7個解：x = ['0.9981', '2.0023', '-1.0020', '1.0036']
第8個解：x = ['1.0006', '1.9987', '-0.9990', '0.9989']
第9個解：x = ['0.9997', '2.0004', '-1.0004', '1.0006']
第10個解：x = ['1.0001', '1.9998', '-0.9998', '0.9998']
第11個解：x = ['0.9999', '2.0001', '-1.0001', '1.0001']
第12個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']
第13個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']
第14個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']
第15個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']
第16個解：x = ['1.0000', '2.0000'

In [ ]:
import numpy as np

#def construct_matrix_A(N):
#    A = np.zeros((N, N))
#    for i in range(N):
#        A[i, i] = 2 * (i + 1)
#        if i + 2 < N:
#            A[i, i + 2] = 0.5 * (i + 1)
#            A[i + 2, i] = 0.5 * (i + 3)
#        if i + 4 < N:
#            A[i, i + 4] = 0.25 * (i + 1)
#            A[i + 4, i] = 0.25 * (i + 5)
#    return A

def sor(A, b, omega, tol=10**(-6), max_iterations=100000):
    N = len(A)
    x = np.zeros(N)
    x_new = np.copy(x)
    x_solution = []

    for iteration in range(max_iterations):
        for i in range(N):
            sums = np.dot(A[i, :i], x_new[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sums)

        # 計算infinite norm
        diff = x_new - x
        max_diff = max(abs(diff))

        #紀錄x的值
        x_solution.append(np.copy(x))

        if max_diff < tol:
            return x_new, iteration + 1, max_diff, x_solution
        else:
           x = np.copy(x_new)

    return x, max_iterations, max_diff, x_solution

N = 4
A = np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
b = [6,25,-11,15]

omegas = [1.0]
results = []

for omega in omegas:
    solution, iterations, norm, x_solution = sor(A, b, omega)
    results.append((omega, iterations, norm))

print("矩陣Ａ是")
print(A)

# 輸出結果
print("This way is Guass-Seidel Iterative")
for result in results:
    print(f"Omega: {result[0]}, Iterations: {result[1]}, Final Norm: {result[2]:.10f}")

i = 0
for x in x_solution:
    formatted_x = [f"{val:.4f}" for val in x]
    print(f"第{i}個解：x = {formatted_x}")
    i += 1

#print(solution)

矩陣Ａ是
[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]]
This way is Guass-Seidel Iterative
Omega: 1.0, Iterations: 8, Final Norm: 0.0000006221
第0個解：x = ['0.0000', '0.0000', '0.0000', '0.0000']
第1個解：x = ['0.6000', '2.3273', '-0.9873', '0.8789']
第2個解：x = ['1.0302', '2.0369', '-1.0145', '0.9843']
第3個解：x = ['1.0066', '2.0036', '-1.0025', '0.9984']
第4個解：x = ['1.0009', '2.0003', '-1.0003', '0.9998']
第5個解：x = ['1.0001', '2.0000', '-1.0000', '1.0000']
第6個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']
第7個解：x = ['1.0000', '2.0000', '-1.0000', '1.0000']


看起來這兩個範例的結果與老師給的結果是一樣吻合的，所以可以確認我的程式碼應該沒有問題

## 接下來我想觀察 $ω$ 變化所帶來的影響，矩陣是用老師所提供的範例，比較簡單的版本

In [ ]:
import numpy as np

#def construct_matrix_A(N):
#    A = np.zeros((N, N))
#    for i in range(N):
#        A[i, i] = 2 * (i + 1)
#        if i + 2 < N:
#            A[i, i + 2] = 0.5 * (i + 1)
#            A[i + 2, i] = 0.5 * (i + 3)
#        if i + 4 < N:
#            A[i, i + 4] = 0.25 * (i + 1)
#            A[i + 4, i] = 0.25 * (i + 5)
#    return A

def sor(A, b, omega, tol=10**(-6), max_iterations=100000):
    N = len(A)
    x = np.zeros(N)
    x_new = np.copy(x)

    for iteration in range(max_iterations):
        for i in range(N):
            sums = np.dot(A[i, :i], x_new[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sums)

        # 計算infinite norm
        diff = x_new - x
        max_diff = max(abs(diff))

        if max_diff < tol:
            return x_new, iteration + 1, max_diff
        else:
           x = np.copy(x_new)

    return x, max_iterations, max_diff

N = 4
A = np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
b = [6,25,-11,15]

omegas = [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
results = []

for omega in omegas:
    solution, iterations, norm = sor(A, b, omega)
    results.append((omega, iterations, norm))

print(A)

# 輸出結果
for result in results:
    print(f"Omega: {result[0]}, Iterations: {result[1]}, Final Norm: {result[2]:.10f}")

#print(solution)

[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]]
Omega: 0.7, Iterations: 17, Final Norm: 0.0000004479
Omega: 0.8, Iterations: 13, Final Norm: 0.0000004067
Omega: 0.9, Iterations: 11, Final Norm: 0.0000005430
Omega: 1.0, Iterations: 8, Final Norm: 0.0000006221
Omega: 1.1, Iterations: 9, Final Norm: 0.0000002439
Omega: 1.2, Iterations: 12, Final Norm: 0.0000002558
Omega: 1.3, Iterations: 15, Final Norm: 0.0000003819
Omega: 1.4, Iterations: 19, Final Norm: 0.0000004482


上課有提到 $ ω $ 的調整是為了考慮新資料與舊資料去做權重的調整，如果已經得到新資料 $ x_{i} $了，則後續的 $ x_{j} $ 資料應該考慮新的 $ x_{i} $ 資料，因為我們相信新的 $ x_{i} $ 一定比舊的 $ x_{i} $ 來的好，所以我們要用新的 $ x_{i} $ 但到底要考慮多少比例，這就涉及 $ ω $ 的值了，而由上面程式可以發現，$ ω $ 太小或太大都不會加速我們得到正確的解答，也就是收斂速度不會變快，因此我們要自己去選取適當的 $ ω $ 來節省我們的運算時間。