Problem\
Use the conjugate gradient method to solve the linear system $ Ax=b $, where the entries of $ A $ and $ b $ are

$$
a_{i,j} =
\begin{cases}
2i, &\text{ when } j=i \text{ and } i = 1,2,....40,\\
-1, &\text{ when}
\begin{cases}
j = i + 1 \text{ and } i = 1,3,...,39,\\
j = i - 1 \text{ and } i = 2,4,...,40,\\
\end{cases}\\
0, &\text{  otherwise,}\\
\end{cases}
$$

and $b_{i} = 1.5i-6 $ , for each  $  i=1,...,40 .$

* (Optional) Use preconditioning with $C^{-1} = D^{-1/2}$

#以下是作業的解答，但我們還需要做一些確認，確認我的程式碼是沒有問題的

In [ ]:
import numpy as np
import time

def conjugate_gradient(A, b, tol=1e-10, max_iter=1000):
    x = np.zeros_like(b, dtype=np.float64)
    r = b - np.dot(A, x)
    v = r.copy()
    rdot = np.dot(r, r)

    for i in range(max_iter):
        Av = np.dot(A, v)
        t = rdot / np.dot(v, Av)
        x += t * v
        r -= t * Av
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        v = r + (rsnew / rdot) * v
        rdot = rsnew
    return x

# 定義矩陣大小
n = 40

# 建立對角線元素
diagonal = np.array([2 * i for i in range(1, n + 1)])
off_diagonal = -1 * np.ones(n - 1)

# 建立矩陣Ａ
A = np.diag(diagonal) + np.diag(off_diagonal, k=1) + np.diag(off_diagonal, k=-1)

# 給定向量b
b = np.array([1.5 * i - 6 for i in range(1, n + 1)])

# 記錄時間
start_time = time.time()

x = conjugate_gradient(A, b)

end_time = time.time()

print("矩陣Ａ是")
print(A)
print("向量b是")
print(b)

# 輸出解
print("x的解是")
print(x)

# 計算時間
print("Conjugate Gradient Method took {:.6f} seconds".format(end_time - start_time))



矩陣Ａ是
[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 76. -1.  0.]
 [ 0.  0.  0. ... -1. 78. -1.]
 [ 0.  0.  0. ...  0. -1. 80.]]
向量b是
[-4.5 -3.  -1.5  0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.
 16.5 18.  19.5 21.  22.5 24.  25.5 27.  28.5 30.  31.5 33.  34.5 36.
 37.5 39.  40.5 42.  43.5 45.  46.5 48.  49.5 51.  52.5 54. ]
x的解是
[-3.0761179  -1.6522358  -0.53282532 -0.04471609  0.17509661  0.29568223
  0.37309011  0.42757934  0.46817927  0.49964748  0.52477026  0.54529835
  0.56239007  0.57684345  0.58922662  0.59995522  0.60934045  0.61761997
  0.62497846  0.63156161  0.63748588  0.64284553  0.64771764  0.65216585
  0.6562432   0.65999423  0.6634566   0.66666242  0.66963919  0.67241061
  0.67499722  0.67741692  0.67968535  0.68181628  0.68382184  0.68571278
  0.68749864  0.68918652  0.69067718  0.68363346]
Conjugate Gradient Method took 0.001174 seconds


## 先檢查矩陣Ａ跟向量Ｂ輸出是否正確

In [ ]:
import numpy as np
import time

def conjugate_gradient(A, b, tol=1e-10, max_iter=1000):
    x = np.zeros_like(b, dtype=np.float64)
    r = b - np.dot(A, x)
    v = r.copy()
    rdot = np.dot(r, r)

    for i in range(max_iter):
        Av = np.dot(A, v)
        t = rdot / np.dot(v, Av)
        x += t * v
        r -= t * Av
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        v = r + (rsnew / rdot) * v
        rdot = rsnew
    return x

# 定義矩陣大小
n = 40

# 建立對角線元素
diagonal = np.array([2 * i for i in range(1, n + 1)])
off_diagonal = -1 * np.ones(n - 1)

# 建立矩陣Ａ
A = np.diag(diagonal) + np.diag(off_diagonal, k=1) + np.diag(off_diagonal, k=-1)

# 給定向量b
b = np.array([1.5 * i - 6 for i in range(1, n + 1)])

# 記錄時間
start_time = time.time()

x = conjugate_gradient(A, b)

end_time = time.time()

# 輸出解
#print(x)

# 計算時間
#print("Conjugate Gradient Method took {:.6f} seconds".format(end_time - start_time))

print("矩陣Ａ是")
print(A)
print("向量b是")
print(b)

矩陣Ａ是
[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 76. -1.  0.]
 [ 0.  0.  0. ... -1. 78. -1.]
 [ 0.  0.  0. ...  0. -1. 80.]]
向量b是
[-4.5 -3.  -1.5  0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.
 16.5 18.  19.5 21.  22.5 24.  25.5 27.  28.5 30.  31.5 33.  34.5 36.
 37.5 39.  40.5 42.  43.5 45.  46.5 48.  49.5 51.  52.5 54. ]


看來是沒問題的

## 接下來跑跑看老師給的例子，看是否正確

In [ ]:
import numpy as np
import time

def conjugate_gradient(A, b, tol=1e-10, max_iter=1000):
    x = np.zeros_like(b, dtype=np.float64)
    r = b - np.dot(A, x)
    v = r.copy()
    rdot = np.dot(r, r)

    for i in range(max_iter):
        Av = np.dot(A, v)
        t = rdot / np.dot(v, Av)
        x += t * v
        r -= t * Av
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        v = r + (rsnew / rdot) * v
        rdot = rsnew
    return x

# 建立矩陣Ａ
A = np.array([[0.2, 0.1, 1, 1, 0],
              [0.1, 4, -1, 1, -1],
              [1, -1, 60, 0, -2],
              [1, 1, 0, 8, 4],
              [0, -1, -2, 4, 700]])

# 給定向量b
b = np.array([1, 2, 3, 4, 5])

# 記錄時間
start_time = time.time()

x = conjugate_gradient(A, b)

end_time = time.time()


print("矩陣Ａ是")
print(A)
print("向量b是")
print(b)

# 輸出解
print("x的解是")
print(x)

# 計算時間
print("Conjugate Gradient Method took {:.6f} seconds".format(end_time - start_time))



矩陣Ａ是
[[ 2.e-01  1.e-01  1.e+00  1.e+00  0.e+00]
 [ 1.e-01  4.e+00 -1.e+00  1.e+00 -1.e+00]
 [ 1.e+00 -1.e+00  6.e+01  0.e+00 -2.e+00]
 [ 1.e+00  1.e+00  0.e+00  8.e+00  4.e+00]
 [ 0.e+00 -1.e+00 -2.e+00  4.e+00  7.e+02]]
向量b是
[1 2 3 4 5]
x的解是
[ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062616]
Conjugate Gradient Method took 0.003757 seconds


這邊看起來是跟老師給的答案是一樣的，所以我的程式碼應該是沒問題的

#接下來我們要進行加速運行，我們先拿範例做preconditioning加速，這裡我們取 $ C^{-1} = D^{-1/2} $

In [ ]:
import numpy as np
import time

def conjugate_gradient(A, b, tol=1e-10, max_iter=1000):
    x = np.zeros_like(b, dtype=np.float64)
    r = b - np.dot(A, x)
    v = r.copy()
    rdot = np.dot(r, r)

    for i in range(max_iter):
        Av = np.dot(A, v)
        t = rdot / np.dot(v, Av)
        x += t * v
        r -= t * Av
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        v = r + (rsnew / rdot) * v
        rdot = rsnew
    return x

# 建立矩陣Ａ
A = np.array([[0.2, 0.1, 1, 1, 0],
              [0.1, 4, -1, 1, -1],
              [1, -1, 60, 0, -2],
              [1, 1, 0, 8, 4],
              [0, -1, -2, 4, 700]])
# 向量b
b = np.array([1, 2, 3, 4, 5])

# 使用preconditioning  C^{-1} = D^{-1/2}
diagonal = np.diag(A)
D_inv_sqrt = np.diag(1 / np.sqrt(diagonal))
M = np.dot(np.dot(D_inv_sqrt, A), D_inv_sqrt)
b_precond = np.dot(D_inv_sqrt, b)

# 記錄時間
start_time = time.time()

x_precond = conjugate_gradient(M, b_precond)

x = np.dot(D_inv_sqrt, x_precond)

end_time = time.time()

print("矩陣Ａ是")
print(A)
print("向量b是")
print(b)

# 輸出解
print("x的解是")
print(x)

# 計算時間
print("Preconditioned Conjugate Gradient Method took {:.6f} seconds".format(end_time - start_time))


矩陣Ａ是
[[ 2.e-01  1.e-01  1.e+00  1.e+00  0.e+00]
 [ 1.e-01  4.e+00 -1.e+00  1.e+00 -1.e+00]
 [ 1.e+00 -1.e+00  6.e+01  0.e+00 -2.e+00]
 [ 1.e+00  1.e+00  0.e+00  8.e+00  4.e+00]
 [ 0.e+00 -1.e+00 -2.e+00  4.e+00  7.e+02]]
向量b是
[1 2 3 4 5]
x的解是
[ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062616]
Preconditioned Conjugate Gradient Method took 0.000386 seconds


可以發現答案是對的，所以程式碼應該是沒問題的，接下來我們也發現運行時間確實比較短，所以有達到我們想加速的效果

那麼現在回答原來的題目，進行preconditioning加速，這裡我們一樣取 $ C^{−1} = D^{−1/2} $

In [ ]:
import numpy as np
import time

def conjugate_gradient(A, b, tol=1e-10, max_iter=1000):
    x = np.zeros_like(b, dtype=np.float64)
    r = b - np.dot(A, x)
    v = r.copy()
    rdot = np.dot(r, r)

    for i in range(max_iter):
        Av = np.dot(A, v)
        t = rdot / np.dot(v, Av)
        x += t * v
        r -= t * Av
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        v = r + (rsnew / rdot) * v
        rdot = rsnew
    return x

# 定義矩陣大小
n = 40

# 建立對角線元素
diagonal = np.array([2 * i for i in range(1, n + 1)])
off_diagonal = -1 * np.ones(n - 1)

# 建立矩陣Ａ
A = np.diag(diagonal) + np.diag(off_diagonal, k=1) + np.diag(off_diagonal, k=-1)

# 給定向量b
b = np.array([1.5 * i - 6 for i in range(1, n + 1)])

# 使用preconditioning  C^{-1} = D^{-1/2}
diagonal = np.diag(A)
D_inv_sqrt = np.diag(1 / np.sqrt(diagonal))
M = np.dot(np.dot(D_inv_sqrt, A), D_inv_sqrt)
b_precond = np.dot(D_inv_sqrt, b)

# 記錄時間
start_time = time.time()

x_precond = conjugate_gradient(M, b_precond)

x = np.dot(D_inv_sqrt, x_precond)

end_time = time.time()

print("矩陣Ａ是")
print(A)
print("向量b是")
print(b)

# 輸出解
print("x的解是")
print(x)

# 計算時間
print("Preconditioned Conjugate Gradient Method took {:.6f} seconds".format(end_time - start_time))


矩陣Ａ是
[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 76. -1.  0.]
 [ 0.  0.  0. ... -1. 78. -1.]
 [ 0.  0.  0. ...  0. -1. 80.]]
向量b是
[-4.5 -3.  -1.5  0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.
 16.5 18.  19.5 21.  22.5 24.  25.5 27.  28.5 30.  31.5 33.  34.5 36.
 37.5 39.  40.5 42.  43.5 45.  46.5 48.  49.5 51.  52.5 54. ]
x的解是
[-3.0761179  -1.6522358  -0.53282532 -0.04471609  0.17509661  0.29568223
  0.37309011  0.42757934  0.46817927  0.49964748  0.52477026  0.54529835
  0.56239007  0.57684345  0.58922662  0.59995522  0.60934045  0.61761997
  0.62497846  0.63156161  0.63748588  0.64284553  0.64771764  0.65216585
  0.6562432   0.65999423  0.6634566   0.66666242  0.66963919  0.67241061
  0.67499722  0.67741692  0.67968535  0.68181628  0.68382184  0.68571278
  0.68749864  0.68918652  0.69067718  0.68363346]
Preconditioned Conjugate Gradient Method took 0.000580 seconds


那這裡我們進行preconditioning加速後，時間縮短了至少一半，所以可以發現我們真的能用preconditioning加速去有效的減少時間，但是我們的 $ C^{-1} $ 的選取會影響我們加速的好壞，那我在這裡就沒有去做其他的 $ C^{-1} $ 選取去檢驗加速效果的差別了